SUSE-Cloud/openstack-quickstart

- scripts/openstack-quickstart-demosetup
Running quickstart in a multinode setup may need more database
connections.
> Increase postgres max db connections

- scripts/openstack-quickstart-demosetup
Nova API v2.1 is needed but is only enabled if also v3 is enabled.
This fixes:
$ nova --os-tenant-name admin secgroup-add-rule default icmp -1 -1 0.0.0.0/0
ERROR (ClientException): The server has either erred or is incapable of performing the requested operation
nova-api.log has:
TRACE nova.api.openstack AttributeError: 'APIRouterV21' object has no attribute '_router'
> Enable Nova API V3 (and V2.1)

- scripts/openstack-quickstart-demosetup
- use share_volume_fstype ext3. Useful if you use a SLE11SP3 based
service image
- set correct interface driver. we use linuxbridge for quickstart
- set correct service project name for cinder and neutron. The name
is needed, not the id
> Fixes for manila

- scripts/openstack-quickstart-demosetup
We have added the deactivate image feature to glance
and also added tempest tests for the same, and this patch
enables to test the feature in tempest config.
https://review.openstack.org/#/c/132717/
https://review.openstack.org/#/c/183700/
> Enables deactivate image test

- scripts/openstack-quickstart-demosetup
We have backported the deactivate image feature to Cloud 5
and also added tempest tests for the same, and this patch
enables to test the feature in tempest config.
https://review.openstack.org/#/c/132717/
https://review.openstack.org/#/c/183700/
(cherry picked from commit 9def69ef480390c5f545913701baa94a3461d9a1)
> [kilo] Enables deactivate image test

- scripts/openstack-quickstart-demosetup
We have backported the deactivate image feature to Cloud 5
and also added tempest tests for the same, and this patch
enables to test the feature in tempest config.
https://review.openstack.org/#/c/132717/
https://review.openstack.org/#/c/183700/
(cherry picked from commit 9def69ef480390c5f545913701baa94a3461d9a1)
> [juno] Enables deactivate image test

- scripts/keystone_data.sh
During the Liberty cycle, Manila added a new API version (v2) which
is now the default.
> Deploy Manila V2 API

- scripts/openstack-quickstart-demosetup
Manila uses the new tempest plugin interface to add tempest tests.
So when running "testr list-tests" or "testr run", the tests need
to be installed.
This fixes:
ImportError: No module named manila_tempest_tests.plugin
> Install manila tempest tests

- scripts/openstack-quickstart-demosetup
otherwise it would fail in ifup on SP1 and Leap 42.1
with "brq... device-unconfigured"
> restart wickedd before ifup

- scripts/openstack-quickstart-demosetup
nova-objectstore was removed upstream and moved to an extra project
called ec2-api. Use the package and service from openstack-ec2-api now.
> Use ec2-api-s3 instead of removed nova-objectstore

- scripts/openstack-loopback-lvm
When setting CINDER_VOLUMES_DEV and/or MANILA_SHARES_DEV, the string set
by theses variables is used as backing device when creating the LVM
volume group during setup.
(cherry picked from commit 401cea596142bc837f58438d9f1ade66cf937a44)
> Allow specific devices for cinder and manila VGs

- scripts/openstack-quickstart-demosetup
We no longer need this code since our packages ship a working `barbican-api-paste.ini` as of today.
> Removed barbican-api-paste.ini handling.

- lib/functions.sh
Postgres got a .service file recently and our current approach didn't stop
native systemd services. But postgres needs a restart because change
i.e. the listen address.
So fix the stop_and_disable_service() function and also stop systemd services.
> Use systemd if available to stop service

- scripts/openstack-quickstart-demosetup
Upstream removed the eventlet based server and a (u)wsgi server is now
required. So use Apache with mod_wsgi to run keystone.
> Fixes for Newton

- scripts/openstack-quickstart-demosetup
This fix following error
```
neutron.services.service_base [-] No providers specified for 'LOADBALANCERV2' service, exiting
```
To fully switch to LoadBalancerPluginv2 service, we have to change
`service_provider` option in `neutron_lbaas.conf` and start right
`openstack-neutron-lbaasv2-agent` service.
> Fix service_provider and start OpenStack Neutron Lbaas v2 agent

- scripts/openstack-quickstart-demosetup
This fix following error
neutron.services.service_base [-] No providers specified for 'LOADBALANCERV2' service, exiting
To fully switch to LoadBalancerPluginv2 service, we have to change
service_provider option in neutron_lbaas.conf and start right
openstack-neutron-lbaasv2-agent service.
(cherry picked from commit 31823c901e8cc742cc8c75ad2c2f65526d22f0b8)
> [mitaka] Fix service_provider and start OpenStack Neutron Lbaas v2 agent

- scripts/openstack-quickstart-demosetup
For OpenStack Mitaka option service_provider for Neutron Lbaas v2
service has to be configured, before openstack-neutron server will
be started.
> [mitaka] Re-organize options for OpenStack Neutron Lbaas v2 service

- scripts/openstack-quickstart-demosetup
For OpenStack Mitaka option service_provider for Neutron Lbaas v2
service has to be configured, before openstack-neutron server will
be started.
(cherry-picked from 53d9f8549d1dcf1ade1079ef56b1bc8086a6d324)
Conflicts:
scripts/openstack-quickstart-demosetup
> Re-organize options for OpenStack Neutron Lbaas v2 service

- scripts/openstack-quickstart-demosetup
V1 is no longer available and the default service provider in neutron-lbaas
is V2.
Conflicts:
scripts/openstack-quickstart-demosetup
(cherry-picked from 15ac55f3eb2a47d8e43811957272e0992219b292)
> [mitaka] Switch to LoadBalancerPluginv2 service plugin

- scripts/keystone_data.sh
Keystone supports $(project_id)s in the catalog. It works the same as $(tenant_id)s. Use of $(tenant_id)s is deprecated and catalog endpoints should be updated to use $(project_id)s.
This PR reflects the changes done in https://github.com/crowbar/crowbar-openstack/pull/587 and makes sure cleanvm also uses $(project_id)s during endpoint registration.
> replace (tenant_id) with (project_id) in service endpoint registration urls

- scripts/keystone_data.sh
This change mirrors the addition of the v3 cinder endpoint introduced by https://github.com/crowbar/crowbar-openstack/pull/596
> cinder: register cinder v3 service and endpoint

- scripts/openstack-quickstart-demosetup
Single backend support is no longer available so "enabled_backends" must
be set and a backend must be configured.
> Configure and enable a cinder backend

- scripts/openstack-quickstart-demosetup
This is needed because neutron has now a symlink called
/etc/neutron/plugin.ini which points to the used core plugin.
When looping over the .ini files, the symlink should not be destroyed.
> Follow symlinks when changing files inplace with sed

- lib/functions.sh
- scripts/openstack-quickstart-demosetup
When kvm can not be used, use qemu instead of lxc. lxc does
not work we we do not have lxc packages available.
> Use qemu instead of lxc as virt_type fallback

- scripts/openstack-quickstart-demosetup
- epmd listens only on the loopback interface which is not enough for
rabbitmq-server .
- With latest rabbitmq(3.6.6)/erlang(19.2.2), starting rabbitmq-server
fails with "init terminating in do_boot". The workaround is to install
the package rabbitmq-server-plugins .
> Workaround rabbitmq startup problems

- scripts/openstack-quickstart-demosetup
The Liberty cleanvm jenkins job has been failing because the ISCSI daemon was not started and so nova could not boot from volume. This is a cherry-pick from https://github.com/SUSE-Cloud/openstack-quickstart/pull/55 which should hopefully resolve the issue.
> Fix startup of iscsid service

- scripts/openstack-quickstart-demosetup
This commit moves the /identity and /identity_damin aliases into
the appropriate <VirtualHost> directives. In their previous location
they applied globally and broke Horizon on setups deployed by
openstack-quickstart.
> Move aliases inside Keystone vhost configuration

- scripts/openstack-quickstart-demosetup
python-novaclient no longer supports this operation and fails with:
error: argument <subcommand>: invalid choice: u'secgroup-add-rule'
> Use openstackclient to create security group rules

- scripts/openstack-quickstart-demosetup
The file from the package moved to
/etc/apache2/vhosts.d/barbican-api.conf.sample so copy that file.
> Copy correct barbican-api.conf vhost file

- etc/bash.openstackrc
- lib/functions.sh
- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
neutron CLI is deprecated and fails currently with Queens in
openstack-quickstart with:
neutron net-create fixed --tenant-id 87ed5237568443d7bc4f11a73f2eb526 \
--shared --provider:network_type vlan \
--provider:segmentation_id 999 \
--provider:physical_network physnet1
neutron CLI is deprecated and will be removed in the future. Use openstack CLI
(http://127.0.0.1:5000/v2.0/tokens): The resource could not be
found. (HTTP 404)
(Request-ID: req-dc216882-e9e2-4594-9806-8aa853b446b5)
> Use openstack instead of neutron client

- scripts/openstack-quickstart-demosetup
In Queens, only identity v3 is available.
> Use auth_version v3 in tempest.conf

- scripts/openstack-quickstart-demosetup
Tests for openstack-neutron-neutron-fwaas have been separated
out into openstack-neutron-neutron-fwaas-test, which must be
installed explicitly. Otherwise tempest's test detection will
fail to find these tests and cause `stestr list` to exit
nonzero.
Please do not merge, yet. During testing I got past the point where `stestr list` failed, but now I'm getting test failures for various fwaas tests. Hence I may need to add more code to this PR to take care of these.
> quickstart: install openstack-neutron-fwaas-test

- scripts/openstack-quickstart-demosetup
Tests for openstack-neutron-neutron-fwaas have been separated
out into openstack-neutron-neutron-fwaas-test, which must be
installed explicitly. Otherwise tempest's test detection will
fail to find these tests and cause `stestr list` to exit
nonzero.
Also, neutron-fwaas was entirely unconfigured. This commit
configures neutron-l3-agent and neutron-server to enable
fwaas. Without this, the fwaas tempest plugin would get
detected and unsuccesfully try to run the fwaas tempest tests.
(cherry picked from commit 4aabced3cec59f5ca10a655f20269097da58278a)
> quickstart: set up neutron-fwaas

- scripts/openstack-quickstart-demosetup
Just a mere week after we enabled FWaaSv1 in quickstart upstream
decided to finally remove FWaaSv1 and ship only FWaaSv2. so
we need to switch to the non-deprecated and non-removed implementation.
> Switch to FWaasV2 implementation

- scripts/openstack-quickstart-demosetup
Designate is not configured and the tempest tests are currently
failing. So disable the plugin for now.
> Disable designate tempest plugin for now

- scripts/openstack-quickstart-demosetup
Recently we switched to singlespec, so we need to pick
python3 or python2 depending on the distribution. Let
the pattern-OpenStackClient figure that out
> Stop installing python-designateclient

- lib/functions.sh
Without this patch, the script emits deprecation warnings about using
the openstackclient 'role list' command, which causes noise in the logs.
This change updates the role queries to use the 'role assignment list'
command and also adds the --format option so that we don't have to parse
the prettytable output. Also updates the group role assignment list
queries to consistently use the long-format flag names.
> Update role assignment list command

- scripts/openstack-quickstart-demosetup
Config options named after keystone 'tenants' were removed[1] and replace
with options named after keystone 'projects'. The result of not setting
the 'project' options was that tempest auth requests would be 'unscoped'
and by default not result in a catalog[2], which meant that it could not
look up service endpoints and would fail with
EndpointNotFound: Endpoint not found
Details: No matching service found in the catalog.
even though the endpoint was in fact in the catalog. This change fixes
the issue by updating the tempest config to use real config options.
[1] https://review.opendev.org/661664
[2] https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#password-authentication-with-unscoped-authorization
> Update keystone config options

- scripts/keystone_data.sh
The automation repo already runs the demosetup script with -x. It just
makes sense to be able to see what the script is doing in the CI.
> Add debug output for keystone data

- scripts/openstack-quickstart-demosetup
Depending on the installed Django package (py2 vs. py3), call the
correct python version to execute the DB migration.
This fixes
ImportError: No module named django.core.management
when calling "python -m ..." in a python3 environment where only
python3-Django is installed.
> Use correct python version when calling django's migrate mgmt cmd

- scripts/openstack-quickstart-demosetup
This was previously done in the rpm package but upstream does not set
a default provider so we won't do that in the package and do it here
now.
> Set a service provider for neutron vpnaas

- scripts/openstack-quickstart-demosetup
It is deprecated[1] and does no longer work so do not deploy it.
[1] https://wiki.openstack.org/wiki/Neutron/LBaaS/Deprecation
> Drop openstack-neutron-lbaasv2 deployment

- scripts/openstack-quickstart-demosetup
The upstream package installs this into /usr/share/barbican
> Use correct location for barbican vhost config

- scripts/openstack-quickstart-demosetup
Don't list "python-<servicename>" on the zypper command to allow the
packages to pick the right dependency when installing the python3
variant.
> Allow python3 for manila, magnum and barbican

- scripts/openstack-quickstart-demosetup
We switched openstack-tempest to be python3 so we need to switch the
plugins to python3, too.
Also drop openstack-tempest-test which is no longer available.
> Install python3 tempest plugins and drop tempest-test package

- scripts/openstack-quickstart-demosetup
To give the db_sync tool a chance to create databases. Otherwise
heat-engine will fail to start.
> Start heat-api before heat-engine

- etc/openstackquickstartrc
- scripts/openstack-quickstart-demosetup
- Add a config parameter (with_ec2api) to be able to disable the
ec2api installation (defaults to yes)
- Setup a database for the EC2 API installation. The DB seems to be
used
- Install openstack-ec2-api-api which does the DB sync
- Do basic configuration in /etc/ec2api/ec2api.conf.d/100-ec2api.conf
> Improve EC2 API installation

- etc/bash.openstackrc
"cinder create" will fail with:
ERROR: You must provide a project_id or project_name ...
if OS_PROJECT_NAME is not set.
> Export OS_PROJECT_NAME

- scripts/openstack-quickstart-demosetup
(backports #111)
Tempest tests for Neutron FWaaS will been enabled in
python-neutron-fwaas, but neutron-fwaas is entirely unconfigured.
This commit configures neutron-l3-agent and neutron-server to enable
fwaas. Without this, the fwaas tempest plugin would get
detected and unsuccesfully try to run the fwaas tempest tests.
(cherry picked from commit 7101d03233e309d0806214c55ff2eac48219e614)
> [newton] quickstart: set up neutron-fwaas

- scripts/openstack-quickstart-demosetup
Installing this package fixes the current Tempest setup failures.
> Install python-neutron-vpnaas-tempest-plugin
