- scripts/openstack-quickstart-demosetup
Wrongly done in ed15240f9326861 .
> Fix max_connections for postgres

- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
- scripts/openstack-quickstart-extranodesetup
The configuration options moved to linuxbridge_agent.ini
> Unblock cleanvm for Cloud:OpenStack:Master

- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
> Add support for Manila

- scripts/keystone_data.sh
keystoneclient CLI is deprecated since 1.3.0 (arround Kilo release). So
use the recommended openstack client for keystone configuration.
See also:
https://github.com/openstack/python-keystoneclient/commit/29c84cdf8
(cherry picked from commit 2a02b852107a87ca97e197e8f9a98c54cc2ee56d)
> Use openstack client

- scripts/openstack-quickstart-demosetup
This fixes a problem when starting the manila-share service.
> Add a manila backend

- scripts/openstack-quickstart-demosetup
Enables manila tests in tempest if manila service is running.
> Enables manila tests

- etc/openstackquickstartrc
- scripts/openstack-quickstart-demosetup
Manila will be installed by default but can be decativated.
> Make manila installation optional

- etc/openstackquickstartrc
- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
This pull request adds the configuration neccessary to get Barbican up and running.
> Added Barbican setup

- scripts/openstack-loopback-lvm
There was recently some extensive changes to qa_openstack.sh but older branches were not fixed to deal with that..
> Backport enough changes to unbreak Kilo

- etc/openstackquickstartrc
- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
Allow to deploy OpenStack Sahara.
> Add more services

- lib/functions.sh
- scripts/openstack-quickstart-demosetup
The packages were udated and now contain only the minimal configuration.
So this commit does:
- update the missing configuration
- use the conf.d/ mechanism to configure services
> Fix configurtation for different services

- etc/openstackquickstartrc
- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
Pull request for master branch
> add monasca support

- etc/openstackquickstartrc
- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
(cherry picked from commit ee58481566b63c5f0bbcd056bdcbfd83df347523)
> Adding support for monasca

- scripts/openstack-quickstart-demosetup
Co-Authored-By: Sumit Jamgade <sjamgade@suse.com>
> Setup monasca-agent

- lib/functions.sh
We have some functions copied from devstack/functions-common [1]
. Sync them.
This also fixes a problem introduced with commit 85914bc8c8 which is:
+ get_or_add_group_project_role member \
5d3d88dc16e7458ab1c9fccf93831dc5 bea50a066f4e45a690b890e6080e5fb7
+ local group_role_id
++ openstack role assignment list --group \
5d3d88dc16e7458ab1c9fccf93831dc5 --project \
bea50a066f4e45a690b890e6080e5fb7  --column ID --format value
No recognized column names in ['ID']. Recognized columns are \
('Role', 'User', 'Group', 'Project', 'Domain', 'System', 'Inherited').
[1] https://github.com/openstack/devstack/blob/master/functions-common
> Sync common functions from devstack

- scripts/openstack-quickstart-demosetup
This has been dropped upstrean in
https://review.opendev.org/#/c/652969/
> remove openstack-nova-consoleauth

- etc/openstackquickstartrc
- scripts/keystone_data.sh
- scripts/openstack-quickstart-demosetup
It was never working and we won't integrate it further. So remove it.
> Drop Gnocchi support

- scripts/openstack-quickstart-demosetup
The upstream neutron-fwaas package is using neutron_fwaas.conf.
> Use correct fwaas config file

- scripts/openstack-quickstart-demosetup
glance-manage is not reading glance-api.conf.d and
glance-registry.conf.d by default.
> Set db connection in glance.conf.d

- scripts/openstack-quickstart-demosetup
> Drop openstack-neutron-fwaas-test package installation

- scripts/openstack-quickstart-demosetup
This package does no longer exist.
> Do not install openstack-manila-test package / Install python3 clients

- scripts/openstack-quickstart-demosetup
The service is no longer available.
> Do no longer setup glance-registry
